export const formattedjoke = (joke: string): string => {
  return joke
    .replace(/- А/, '\n- А')
    .replace(/- Б/, '\n- Б')
    .replace(/- В/, '\n- В')
    .replace(/- Г/, '\n- Г')
    .replace(/- Д/, '\n- Д')
    .replace(/- Е/, '\n- Е')
    .replace(/- Ж/, '\n- Ж')
    .replace(/- З/, '\n- З')
    .replace(/- И/, '\n- И')
    .replace(/- Й/, '\n- Й')
    .replace(/- К/, '\n- К')
    .replace(/- Л/, '\n- Л')
    .replace(/- М/, '\n- М')
    .replace(/- Н/, '\n- Н')
    .replace(/- О/, '\n- О')
    .replace(/- П/, '\n- П')
    .replace(/- Р/, '\n- Р')
    .replace(/- С/, '\n- С')
    .replace(/- Т/, '\n- Т')
    .replace(/- У/, '\n- У')
    .replace(/- Ф/, '\n- Ф')
    .replace(/- Х/, '\n- Х')
    .replace(/- Ц/, '\n- Ц')
    .replace(/- Ч/, '\n- Ч')
    .replace(/- Ш/, '\n- Ш')
    .replace(/- Щ/, '\n- Щ')
    .replace(/- Ю/, '\n- Ю')
    .replace(/- Я/, '\n- Я')
    .replace(/-А/, '\n-А')
    .replace(/-Б/, '\n-Б')
    .replace(/-В/, '\n-В')
    .replace(/-Г/, '\n-Г')
    .replace(/-Д/, '\n-Д')
    .replace(/-Е/, '\n-Е')
    .replace(/-Ж/, '\n-Ж')
    .replace(/-З/, '\n-З')
    .replace(/-И/, '\n-И')
    .replace(/-Й/, '\n-Й')
    .replace(/-К/, '\n-К')
    .replace(/-Л/, '\n-Л')
    .replace(/-М/, '\n-М')
    .replace(/-Н/, '\n-Н')
    .replace(/-О/, '\n-О')
    .replace(/-П/, '\n-П')
    .replace(/-Р/, '\n-Р')
    .replace(/-С/, '\n-С')
    .replace(/-Т/, '\n-Т')
    .replace(/-У/, '\n-У')
    .replace(/-Ф/, '\n-Ф')
    .replace(/-Х/, '\n-Х')
    .replace(/-Ц/, '\n-Ц')
    .replace(/-Ч/, '\n-Ч')
    .replace(/-Ш/, '\n-Ш')
    .replace(/-Щ/, '\n-Щ')
    .replace(/-Ю/, '\n-Ю')
    .replace(/-Я/, '\n-Я')
    .replace(/—/, '\n-');
};
