export const formattedjoke = (joke: string): string => {
  return joke
    .replace(/- А/g, '\n- А')
    .replace(/- Б/g, '\n- Б')
    .replace(/- В/g, '\n- В')
    .replace(/- Г/g, '\n- Г')
    .replace(/- Д/g, '\n- Д')
    .replace(/- Е/g, '\n- Е')
    .replace(/- Ж/g, '\n- Ж')
    .replace(/- З/g, '\n- З')
    .replace(/- И/g, '\n- И')
    .replace(/- Й/g, '\n- Й')
    .replace(/- К/g, '\n- К')
    .replace(/- Л/g, '\n- Л')
    .replace(/- М/g, '\n- М')
    .replace(/- Н/g, '\n- Н')
    .replace(/- О/g, '\n- О')
    .replace(/- П/g, '\n- П')
    .replace(/- Р/g, '\n- Р')
    .replace(/- С/g, '\n- С')
    .replace(/- Т/g, '\n- Т')
    .replace(/- У/g, '\n- У')
    .replace(/- Ф/g, '\n- Ф')
    .replace(/- Х/g, '\n- Х')
    .replace(/- Ц/g, '\n- Ц')
    .replace(/- Ч/g, '\n- Ч')
    .replace(/- Ш/g, '\n- Ш')
    .replace(/- Щ/g, '\n- Щ')
    .replace(/- Ю/g, '\n- Ю')
    .replace(/- Я/g, '\n- Я')
    .replace(/-А/g, '\n-А')
    .replace(/-Б/g, '\n-Б')
    .replace(/-В/g, '\n-В')
    .replace(/-Г/g, '\n-Г')
    .replace(/-Д/g, '\n-Д')
    .replace(/-Е/g, '\n-Е')
    .replace(/-Ж/g, '\n-Ж')
    .replace(/-З/g, '\n-З')
    .replace(/-И/g, '\n-И')
    .replace(/-Й/g, '\n-Й')
    .replace(/-К/g, '\n-К')
    .replace(/-Л/g, '\n-Л')
    .replace(/-М/g, '\n-М')
    .replace(/-Н/g, '\n-Н')
    .replace(/-О/g, '\n-О')
    .replace(/-П/g, '\n-П')
    .replace(/-Р/g, '\n-Р')
    .replace(/-С/g, '\n-С')
    .replace(/-Т/g, '\n-Т')
    .replace(/-У/g, '\n-У')
    .replace(/-Ф/g, '\n-Ф')
    .replace(/-Х/g, '\n-Х')
    .replace(/-Ц/g, '\n-Ц')
    .replace(/-Ч/g, '\n-Ч')
    .replace(/-Ш/g, '\n-Ш')
    .replace(/-Щ/g, '\n-Щ')
    .replace(/-Ю/g, '\n-Ю')
    .replace(/-Я/g, '\n-Я')
    .replace(/—/g, '\n-');
};
